myapp/urls.py
from django.shortcuts import redirect
from django.urls import path
from myapp import views

app_name = 'myapp'
urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'about/', views.about, name='about'),
    path(r'<int:top_no>/', views.detail, name='detail'),
    path(r'courses/', views.courses, name='courses'),
    path(r'place_order/', views.place_order, name='placeorder'),
    path(r'courses/<int:cour_id>/', views.coursedetail, name='course_detail'),
    path(r'login/', views.user_login, name='user_login'),
    path(r'logout/', views.user_logout, name='user_logout'),
    path(r'myaccount/', views.myaccount, name='myaccount'),
    path(r'register/', views.register, name='register'),
    path(r'myorders/', views.myorders, name='myorders'),
    path(r'myaccount//', lambda req: redirect('/myapp/myaccount/')),
    path(r'forgotPassword/', views.forgotPassword, name='forgotPassword'),
]

myapp/models.py
from django.db import models

# Create your models here.
import datetime
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone

class Topic(models.Model):
    name = models.CharField(max_length=200)
    CATEGORY_CHOICES = [('Web Development', 'Development'),
                        ('Management', 'Business'),
                        ('Economics', 'Finance & Accounting'),
                        ('IT Certification', 'IT & Software'),
                        ('Sports', 'Health & Fitness')]
    category = models.CharField(max_length=200,choices=CATEGORY_CHOICES,blank=False,
                                default='')

    def __str__(self):
        return self.name


class Course(models.Model):
     topic = models.ForeignKey(Topic, related_name='courses',
                               on_delete=models.CASCADE)
     name = models.CharField(max_length=200)
     price = models.DecimalField(max_digits=10, decimal_places=2,validators=[MinValueValidator(50),MaxValueValidator(500)])
     for_everyone = models.BooleanField(default=True)
     description = models.TextField(max_length=300, null=True, blank=True)
     interested = models.PositiveIntegerField(default=0)
     stages = models.PositiveIntegerField(default=3)

     def discount(self):
         discount_amt = (10 * self.price) / 100
         discounted_price = self.price - discount_amt
         return discounted_price

     def __str__(self):
         return self.name

class Student(User):
 CITY_CHOICES = [('WS', 'Windsor'),
 ('CG', 'Calgery'),
 ('MR', 'Montreal'),
 ('VC', 'Vancouver')]
 school = models.CharField(max_length=50, null=True, blank=True)
 address = models.CharField(max_length=200, null=True, blank=True)
 city = models.CharField(max_length=2, choices=CITY_CHOICES, default='WS')
 interested_in = models.ManyToManyField(Topic)
 image = models.ImageField(upload_to='static/images/', height_field=None, width_field=None, blank=True, null=True, default= None)

 def __str__(self):
     return '%s %s' % (self.first_name, self.last_name)

class Order(models.Model):
     course = models.ForeignKey(Course, related_name='orders', on_delete=models.CASCADE, default=1)
     student = models.ForeignKey(Student, related_name='students', on_delete=models.CASCADE)
     levels = models.PositiveIntegerField()
     ORDER_CHOICES = [(0, 'Cancelled'),
                      (1, 'Order Confirmed')]
     order_status = models.IntegerField(choices=ORDER_CHOICES, default=1)
     order_date = models.DateField()

     def total_cost(self):
         sum = 0
         for course in self.course:
             sum += course.price
         return sum

     def __str__(self):
         return str(self.id)+"_"+self.student.first_name+"_"+self.student.last_name

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from myapp.models import Order, Student


class InterestForm(forms.Form):
    CHOICES = [(1, 'Yes'), (0, 'No')]
    interested = forms.CharField(label='Interested', widget=forms.RadioSelect(choices=CHOICES))
    levels = forms.IntegerField(label='Levels', initial=1)
    comments = forms.CharField(label='Additional Comments', widget=forms.Textarea, required=False)

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['student','course','levels','order_date']
        student = forms.ChoiceField(widget=forms.RadioSelect())
        order_date = forms.DateField(widget=forms.SelectDateWidget(empty_label="Nothing"))

class RegisterForm(UserCreationForm):
    class Meta:
        model = Student
        fields = ["username", "first_name", "last_name", "password1", "password2"]

myapp/views.py
import datetime
import json
from locale import format

from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404

# Create your views here.
# Import necessary classes
from django.http import HttpResponse, HttpResponseRedirect

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .forms import OrderForm, InterestForm, RegisterForm
from .models import Topic, Course, Student, Order


# Create your views here.
def index(request):
    top_list = Topic.objects.all().order_by('id')[:10]
    top_courses = Course.objects.all().order_by('-price')[:5]
    browserCLose = request.session.get_expire_at_browser_close()
    if 'last_login' in request.session:
        last_login = request.session['last_login']
    else:
        last_login = 0
    # response = HttpResponse()
    # heading1 = '<p>' + '<b>' + 'List of topics: ' + '</b>' + '</p>'
    # response.write(heading1)
    # for topic in top_list:
    #  para = '<p>' + str(topic.id) + ': ' + str(topic) + '</p>'
    #  response.write(para)
    # top_courses = Course.objects.all().order_by('-price')[:5]
    # heading2 = '<p>' + '<b>' + 'List of courses: ' + '</b>' + '</p>'
    # response.write(heading2)
    # for course in top_courses:
    #  para1 = '<p>' + str(course) + '</p>'
    #  if course.for_everyone:
    #   para1 = '<p>' + str(course) + '<i>' + ' - This Course is For Everyone!' + '</i>' + '</p>'
    #   # para1 = para1 + 'This Course is For Everyone!'
    #  else:
    #   para1 = '<p>' + str(course) + '<i>' + ' - This Course is Not For Everyone!' + '</i>' + '</p>'
    #   # para1 = para1 + 'This Course is Not For Everyone!'
    #  # para1 = '<p>' + str(course) + '</p>'
    #  response.write(para1)
    # return response
    return render(request, 'myapp/index.html', {'top_list': top_list, 'top_course': top_courses,
                                                'last_login': last_login, 'browserCLose': browserCLose})


def about(request):
    about_visits = request.COOKIES.get('about_visits')
    if about_visits:
        cookie_count = int(about_visits) + 1
    else:
        cookie_count = 1
    about_response = render(request, 'myapp/about.html', {'count': cookie_count})
    about_response.set_cookie(key='about_visits', value=cookie_count, max_age=300)
    return about_response


# def about(request):
#     # about_response = HttpResponse()
#     # about_content = '<p>' + '<b>' + 'This is an E-learning Website! Search our Topics to find all available Courses.' + '</b>' + '</p> '
#     # about_response.write(about_content)
#     # # return HttpResponse('This is an E-learning Website! Search our Topics to find all available Courses.')
#     # return about_response
#     return render(request, 'myapp/about.html')


def detail(request, top_no):
    # t = get_object_or_404(Topic,id=top_no)
    # t_category = t.get_category_display()
    # courses = Course.objects.filter(topic=top_no)
    # detail_response = HttpResponse()
    # heading1 = '<p>' + '<b>' + 'Category of the topic: ' + '</b>' + '</p>'
    # detail_response.write(heading1)
    # t_para = '<p>' + str(t_category) + '</p>'
    # detail_response.write(t_para)
    # heading2 = '<p>' + '<b>' + 'List of courses of the topic: ' + '</b>' + '</p>'
    # detail_response.write(heading2)
    # for course in courses:
    #  t_para = '<p>' + str(course) + '</p>'
    #  detail_response.write(t_para)
    # return detail_response
    t = get_object_or_404(Topic, id=top_no)
    t_category = t.get_category_display()
    courses = Course.objects.filter(topic=top_no)
    # return render(request, 'myapp/detail0.html', {'topic_category': t_category})
    return render(request, 'myapp/detail.html', {'topic_name': t, 'topic_category': t_category, 'courses': courses})


def courses(request):
    courlist = Course.objects.all().order_by('id')
    return render(request, 'myapp/courses.html', {'courlist': courlist})


def place_order(request):
    msg = ''
    courlist = Course.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if order.levels <= order.course.stages:
                if order.course.price > 150:
                    order.course.discount()
                order.save()
                msg = 'Your course has been ordered successfully.'
            else:
                msg = 'You exceeded the number of levels for this course.'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
    return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'courlist': courlist})


def coursedetail(request, cour_id):
    top_list = Topic.objects.all().order_by('id')[:10]
    top_courses = Course.objects.all().order_by('-price')[:5]
    course_detail = Course.objects.get(id=cour_id)
    interested = course_detail.interested
    if request.method == 'POST':
        myform = InterestForm(request.POST)
        if myform.is_valid():
            form_interested = myform.cleaned_data['interested']
            if int(form_interested) == 1:
                interested += 1
                course_detail.interested = interested
                course_detail.save()
                return render(request, 'myapp/index.html', {'top_list': top_list, 'top_course': top_courses})
                # msg = 'Your course has been ordered successfully.'
    else:
        myform = InterestForm()
    return render(request, 'myapp/coursedetail.html', {'form': myform, 'course_name': course_detail})
    # return render(request, 'myapp/coursedetail.html', {'course_name': course_detail})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()
            # return HttpResponse("You are logged in")
        request.session.set_test_cookie()

        now = datetime.datetime.now()
        json_str = json.dumps(now, default=str)
        request.session['last_login'] = json_str
        request.session.set_expiry(3600)

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('myapp:myaccount'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    logout(request)
    # del request.session['last_login']
    return HttpResponseRedirect(reverse('login'))


@login_required(login_url='/myapp/login/')
def myaccount(request):
    username = request.user

    try:

        curr_student = get_object_or_404(Student, username=username)
        sid = curr_student.id
        course_ordered = Order.objects.filter(student=sid)
        topic_interested = curr_student.interested_in.all()
        return render(request, 'myapp/myaccount.html',
                      {'student': curr_student, 'orders': course_ordered, 'topics': topic_interested})

    except:
        return render(request, 'myapp/myaccount.html')


# def register(request):
#     if request.method == "POST":
#         form = RegisterForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             login(request, user)
#             #messages.success(request, "Registration successful.")
#             return HttpResponseRedirect(reverse('login'))
#         else:
#             return HttpResponse('Registration Unsuccessful. Invalid Information')
#     form = RegisterForm()
#     return render(request, 'myapp/register.html', context={'form': form})

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')

    form = RegisterForm()
    return render(request, 'myapp/register.html', {'form': form})


@login_required
def myorders(request):
    username = request.user

    try:
        curr_student = get_object_or_404(Student, username=username)
        sid = curr_student.id

        course_ordered = Order.objects.filter(student=sid)
        return render(request, 'myapp/myorders.html',
                      {'student': curr_student, 'orders': course_ordered})

    except:
        return render(request, 'myapp/myorders.html')


def forgotPassword(request):
    if request.method == 'POST':
        email = request.POST.get('UserEmail')
        password = "passwordNew"
        user = User.objects.get(email=email)
        user.set_password(password)
        user.save()
        send_mail(
            "New Password",  # subject
            password,  # message
            'lancerguidewindsor@gmail.com',  # from
            [email],  # to
        )
        return HttpResponse("We have emailed you a new password")
    else:
        return render(request, 'myapp/passwordreset.html')

templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block title %}About Page!{% endblock %}
{% block body_block %}

     <p><b>This is an E-learning Website! Search our Topics to find all available Courses.</b></p>
     <p><b>The number of times the About page visited is: </b> {{ count }}</p>

{#    <p><a href="/myapp/">To Main Page (Hardcoded URL)</a></p>#}
{#    <p><a href="{% url 'myapp:index' %}">To Main Page (URL Namespacing)</a></p>#}

{% endblock %}

templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About page</title>
</head>
<body>
<p><b>This is an E-learning Website! Search our Topics to find all available Courses.</b></p>

<p><a href="/myapp/">Index page (Hardcoded URL)</a></p>
<p><a href="{% url 'myapp:index' %}">Index page (URL Namespacing)</a></p>
</body>
</html>

templates/myapp/base.html
<!DOCTYPE html>
{% load static  %}
<html>
 <head>
 <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">
 <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
 </head>
 <body style="background-color:lightgray">
 <div class="container-fluid">

 <h1>
     {% block myhdg %}Hello
         {{ user.first_name }}
     {% endblock %}
 </h1>
    <div class="row">
        <div class="col-sm-3 col-md-3 col-lg-3"></div>
        <div class="col-sm-6 col-md-6 col-lg-6">
            {% block body_block %}*** {% endblock %}
        </div>
        <div class="col-sm-3 col-md-3 col-lg-3"></div>
    </div>

 </div>
 <hr />
 <br /><br />

 <div>
    <nav class="navbar navbar-inverse navbar-fixed-bottom">
       <ul class="nav navbar-nav">
           {% if request.user.is_authenticated %}
               <li class="hbar1"><a href = "{% url 'myapp:user_logout' %}">Logout</a></li>
               <li class="hbar1"><a href = "{% url 'myapp:courses' %}">Click here to see the available courses</a></li>
                <li class="hbar1"><a href = "{% url 'myapp:myorders' %}">My orders</a></li>
           {% else %}
               <li class="hbar1"><a href = "{% url 'myapp:user_login' %}">Login</a></li>
               <li class="hbar1"><a href = "{% url 'myapp:register' %}">Register</a></li>
           {% endif %}
       <li class="hbar1"><a href="/myapp/about/">Find out about our ELearning site</a></li>
       <li class="hbar1"><a href = "{% url 'myapp:index' %}">Home page</a></li>

        <li class="hbar1"><a href = "{% url 'myapp:myaccount' %}">My Account</a></li>
{#       <li class="hbar1"><a href = "{% url 'myapp:myorder' %}">My Orders</a></li>#}
       </ul>
    </nav>
</div>

{# <div>#}
{#     <nav class="navbar navbar-inverse navbar-fixed-bottom">#}
{#     <ul class="nav navbar-nav">#}
{#         <li class="hbar1"><a href="/myapp/about/">Find out about our ELearning site</a></li>#}
{#         <li class="hbar1"><a href="{% url 'myapp:index' %}">Click here to return to main page</a></li>#}
{#         <li class="hbar1"><a href="{% url 'myapp:courses' %}">Click here to see the available courses</a></li>#}
{#         <li class="hbar1"><a href="{% url 'myapp:myaccount' %}">My account</a></li>#}
{#         <li class="hbar1"><a href="{% url 'myapp:user_logout' %}">Logout!</a></li>#}
{#     </ul>#}
{#     </nav>#}
{# </div>#}
</body>
</html>

templates/myapp/coursedetail.html
{% extends 'myapp/base.html' %}

{% block title %}Course Detail Page!{% endblock %}
{% block body_block %}
    <p><b>Course Name: </b>{{ course_name.name }}</p>
    <p><b>Number of interested people: </b>{{ course_name.interested }}</p>
    <p><b>Price: </b>{{ course_name.price }}</p>
    {% if not course_name.for_everyone %}
        <p><b>The course <i>{{ course_name.name }}</i> is not for everyone </b></p>
    {% endif %}

    <form action = "" method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
    <!--<p><a href="/eLearnApp/">To Main Page (Hardcoded URL)</a></p>-->
    <!--<p><a href="{% url 'myapp:index' %}">To Main Page (URL Namespacing)</a></p>-->
{% endblock %}

templates/myapp/courses.html
{% extends 'myapp/base.html' %}

{% block title %}Courses Page!{% endblock %}
{% block body_block %}

    {% if courlist %}
        <p><b>List of available courses are: </b></p>
        <ol class="list-group">
            {% for course in courlist %}
                <li><a href="{% url 'myapp:course_detail' course.id %}" class="list-group-item">{{ course.name }}</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available courses!</strong>
    {% endif %}

    <!--<p><a href="{% url 'myapp:index' %}">To Main Page</a></p>-->

    <li class="hbar1"><a href = "{% url 'myapp:placeorder' %}">Click here to place a new order</a><br/></li>

{% endblock %}

templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block title %}Detail Page!{% endblock %}
{% block body_block %}

    <p><b>Topic Name: </b></p>
    <p>{{ topic_name }}</p>
    <p><b>Category of the topic: </b></p>
    <p>{{ topic_category }}</p>

    {% if courses %}
        <p><b>List of courses of the topic: </b></p>
        <ol class="list-group">
            {% for course in courses %}
                <li class="list-group-item">{{ course.name }}</li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}

    <p><a href="{% url 'myapp:index' %}">To Main Page</a></p>

{% endblock %}

templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details Page</title>
</head>
<body>
    <p><b>Topic Name: </b></p>
    <p>{{ topic_name }}</p>
    <p><b>Category of the topic: </b></p>
    <p>{{ topic_category }}</p>

    {% if courses %}
        <p><b>List of courses of the topic: </b></p>
        <ol>
            {% for course in courses %}
                <li>{{ course.name }}</li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}

    <p><a href="{% url 'myapp:index' %}">To Main Page</a></p>
</body>
</html>

templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if last_login %}
        <p><b>Your Last Login: {{ last_login }}</b></p>
    {% else %}
        <p><b>Your Last Login was more than One Hour ago</b></p>
    {% endif %}
    {% if browserCLose %}
        <p> Session Clear on Browser Close = True</p>
    {% else %}
        <p>Session Clear on Browser Close = False</p>
    {% endif %}

     {% if top_list %}
        <h2>List of Topics</h2>
        <ol class="list-group">
            {% for topics in top_list %}
                <li><a href="{% url 'myapp:detail' topics.id %}" class="list-group-item">{{ topics.name }}</a></li>
            {% endfor %}
        </ol>
        <h2>List of Courses</h2>
        <ol class="list-group">
            {% for course in top_course %}
                <li><a class="list-group-item">{{ course.name }}</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}

{#    <p><a href="{% url 'myapp:about' %}">About page</a></p>#}

{% endblock %}

templates/myapp/index0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>E-Learning WebApp!</title>
</head>
<body>
    {% if top_list %}
        <h2>List of Topics</h2>
        <ol>
            {% for topics in top_list %}
                <li><a href="{% url 'myapp:detail' topics.id %}">{{ topics.name }}</a></li>
            {% endfor %}
        </ol>
        <h2>List of Courses</h2>
        <ol>
            {% for course in top_course %}
                <li>{{ course.name }}</li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}

<!--<p><a href="/eLearnApp/about">About page</a></p>-->
<p><a href="{% url 'myapp:about' %}">About page</a></p>

</body>
</html>

templates/myapp/login.html
{% extends 'myapp/base.html' %}
{% block title %}Login Here{% endblock %}
{% block myhdg %}Login Here {% endblock %}
{% block body_block %}
<br /><br />
                <form action="{% url 'myapp:user_login' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                    <div class="col-sm-3 col-md-3 col-lg-3"></div>
                    <div class="col-sm-2 col-md-2 col-lg-2">
                        <label for="username">Username: </label>
                    </div>
                    <div class="col-sm-4 col-md-4 col-lg-4">
                        <input id="username" type="text" name="username"><br><br>
                    </div>
                    <div class="col-sm-3 col-md-3 col-lg-3"></div>
                    </div>
                    <div class="row">
                    <div class="col-sm-3 col-md-3 col-lg-3"></div>
                    <div class="col-sm-2 col-md-2 col-lg-2">
                        <label for="password">Password: </label>
                    </div>
                    <div class="col-sm-4 col-md-4 col-lg-4">
                        <input id="password" type="password" name="password"><br><br>
                    </div>
                    <div class="col-sm-3 col-md-3 col-lg-3"></div>
                    </div>
                    <div class="row">
                        <div class="col-sm-3 col-md-3 col-lg-3"></div>
                        <div class="col-sm-9 col-md-9 col-lg-9">
                            <input type="submit" value="Login"><br><br>
                        </div>
                    </div>


                </form>
                <div class="row">
                        <div class="col-sm-3 col-md-3 col-lg-3"></div>
                        <div class="col-sm-9 col-md-9 col-lg-9">
                            <p><a href="{% url 'myapp:forgotPassword' %}">Forgot Password</a></p>
                        </div>
                    </div>


{% endblock%}
{#<!DOCTYPE html>#}
{#<html>#}
{#<head>#}
{#<link rel="stylesheet" type="text/css" href="myapp/style.css">#}
{# <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>#}
{# <meta charset="utf-8">#}
{#  <meta name="viewport" content="width=device-width, initial-scale=1">#}
{#  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">#}
{#  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>#}
{#  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>#}
{#    <style>#}
{##}
{#body{#}
{#    background-color: lightblue;#}
{#    background-position: center;#}
{#    background-repeat: no-repeat;#}
{#    background-size: cover;#}
{#    margin: 0;#}
{#    padding-left: 10px;#}
{# </style>#}
{#</head>#}
{#<body>#}
{#<div class="container-fluid">#}
{#    <div class="row">#}
{#    <div class="col-sm-3 col-md-3 col-lg-3"></div>#}
{#    <div class="col-sm-6 col-md-6 col-lg-6">#}
{#        <br /><h2>Login Here</h2><br /><br />#}
{#        <form action="{% url 'myapp:user_login' %}" method="post">#}
{#         {% csrf_token %}#}
{#         <label for="username">Username: </label>#}
{#         <input id="username" type="text" name="username"><br /><br />#}
{#         <label for="password">Password: </label>#}
{#         <input id="password" type="password" name="password">#}
{#         <input type="submit" value="Login"><br />#}
{#    </form>#}
{#    <br /><a href="{% url 'myapp:register' %}">Register</a>#}
{#    </div>#}
{#    <div class="col-sm-3 col-md-3 col-lg-3"></div>#}
{##}
{#    </div>#}
{#</div>#}
{#</body>#}
{#</html>#}

templates/myapp/myaccount.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if student %}
        <div>&nbsp; &nbsp;<span>First Name - {{ student.first_name }} </span> </div>
        <div>&nbsp; &nbsp;<span>Last Name - {{ student.last_name }} </span> </div>
        {% if orders %}
            <h2> Courses Ordered</h2>
            {% for order in orders %}
                <div>&nbsp; &nbsp;<span>Name - {{ order.course.name }} </span> </div>
                <div>&nbsp; &nbsp;<span>Price - {{ order.course.price }} </span> </div>
                <br>
            {% endfor %}
        {% endif %}

        {% if topics %}
            <h2> Interested Topics</h2>
            {% for topic in topics %}
                <div>&nbsp; &nbsp;<span>Name - {{ topic.name }} </span> </div>
                <div>&nbsp; &nbsp;<span>Category - {{ topic.category }} </span> </div>
                <br>
            {% endfor %}
        {% endif %}

    {% else %}
        <strong> You are not a registered student!!</strong>
    {% endif %}


{% endblock %}

templates/myapp/myorders.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if student %}
        <div>&nbsp; &nbsp;<span>First Name - {{ student.first_name }} </span> </div>
        <div>&nbsp; &nbsp;<span>Last Name - {{ student.last_name }} </span> </div>
        {% if orders %}
            <h2> Courses Ordered</h2>
            {% for order in orders %}
                <div>&nbsp; &nbsp;<span>Name - {{ order.course.name }} </span> </div>
                <div>&nbsp; &nbsp;<span>Price - {{ order.course.price }} </span> </div>
                <br>
            {% endfor %}
        {% endif %}

    {% else %}
        <strong> You are not a registered student!!</strong>
    {% endif %}

{% endblock %}

templates/myapp/order_response.html
{% extends 'myapp/base.html' %}

{% block title %}About Page!{% endblock %}
{% block body_block %}
    <p>{{ msg }}</p>
{% endblock %}

templates/myapp/register.html
{% extends 'myapp/base.html' %}
{% block body_block %}

    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
    </form>
{% endblock %}